# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Dame Baseball
email: kevintdame@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kevin Dame is a writer and visual designer who brings sports information to
  life in new and meaningful ways. His work, which has been featured on espn.com,
  Fast Company, and the San Francisco Chronicle, can also be found at The Hardball Times.
  A lifelong Red Sox fan, Kevin currently resides in the San Francisco Bay Area.
  He welcomes your comments, questions and suggestions via email.
baseurl: "/visualbaseball" # the subpath of your site, e.g. /blog
url: "http://http://kevintdame.github.io/visualbaseball" # the base hostname & protocol for your site
twitter_username: kevintdame

# Build settings
markdown: kramdown
